'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://Sample.WCF", ConfigurationName:="ServiceReference1.IMyService")>  _
    Public Interface IMyService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Sample.WCF/IMyService/SayHello", ReplyAction:="http://Sample.WCF/IMyService/SayHelloResponse")>  _
        Function SayHello(ByVal name As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Sample.WCF/IMyService/SayHello", ReplyAction:="http://Sample.WCF/IMyService/SayHelloResponse")>  _
        Function SayHelloAsync(ByVal name As String) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IMyServiceChannel
        Inherits ServiceReference1.IMyService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MyServiceClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.IMyService)
        Implements ServiceReference1.IMyService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function SayHello(ByVal name As String) As String Implements ServiceReference1.IMyService.SayHello
            Return MyBase.Channel.SayHello(name)
        End Function
        
        Public Function SayHelloAsync(ByVal name As String) As System.Threading.Tasks.Task(Of String) Implements ServiceReference1.IMyService.SayHelloAsync
            Return MyBase.Channel.SayHelloAsync(name)
        End Function
    End Class
End Namespace
