'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://Sample.WCF", ConfigurationName:="ServiceReference1.IMyService")>  _
    Public Interface IMyService
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://Sample.WCF/IMyService/Regist")>  _
        Sub Regist()
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://Sample.WCF/IMyService/Regist")>  _
        Function RegistAsync() As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Sample.WCF/IMyService/HeavyRegist", ReplyAction:="http://Sample.WCF/IMyService/HeavyRegistResponse")>  _
        Sub HeavyRegist()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Sample.WCF/IMyService/HeavyRegist", ReplyAction:="http://Sample.WCF/IMyService/HeavyRegistResponse")>  _
        Function HeavyRegistAsync() As System.Threading.Tasks.Task
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IMyServiceChannel
        Inherits ServiceReference1.IMyService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MyServiceClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.IMyService)
        Implements ServiceReference1.IMyService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub Regist() Implements ServiceReference1.IMyService.Regist
            MyBase.Channel.Regist
        End Sub
        
        Public Function RegistAsync() As System.Threading.Tasks.Task Implements ServiceReference1.IMyService.RegistAsync
            Return MyBase.Channel.RegistAsync
        End Function
        
        Public Sub HeavyRegist() Implements ServiceReference1.IMyService.HeavyRegist
            MyBase.Channel.HeavyRegist
        End Sub
        
        Public Function HeavyRegistAsync() As System.Threading.Tasks.Task Implements ServiceReference1.IMyService.HeavyRegistAsync
            Return MyBase.Channel.HeavyRegistAsync
        End Function
    End Class
End Namespace
